AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Naming/MethodParameterName:
  AllowedNames:
    - ai
    - to
    - id
